# Terraform docs configuration file
# Only setting non-default values

formatter: "markdown table"
sort:
  by: required
output:
  file: README.md
settings:
  hide-empty: true
  lockfile: false

content: |-
  ## Example Usage

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
